baseurl = "https://mrbobbytabl.es/"
title = "Bob Killen"
copyright = "&copy; 2018"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]
[blackfriday]
  hrefTargetBlank = true
  fractions = true 
  smartypants = true

[params]
  color_theme = "ocean"
  font = "default"

  name = "Bob Killen"
  role = "Senior Research Cloud Administrator"

  organizations = [ { name = "University of Michigan", url = "https://arc-ts.umich.edu/" } ]

  gravatar = false
  avatar = "BobKillen.jpeg"
  email = "bob.killen@linux.com"
  address = "540 E. Liberty, Suite 202, Ann Arbor, MI  48104"
  keybase = "mrbobbytables"
  logo = ""
  map = 0
  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"
  reading_time = true
  comment_count = true
  section_pager = false
  math = false
  highlight = false
  highlight_languages = []
   highlight_style = "github"

  sharing = true
  privacy_pack = false
  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  [params.talks]
    time = true
  [params.publications]
    date_format = "January, 2006"

  [params.projects]
    list_children = true
    publication_format = 3

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:bob.killen@linux.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/mrbobbytables"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/mrbobbytables"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    link = "//linkedin.com/mrbobbytables"

  [[params.social]]
    icon = "medium"
    icon_pack = "fab"
    link = "http://medium.com/@mrbobbytables"  

  [[params.social]]
    icon = "key"
    icon_pack = "fa"
    link = "//keybase.io/mrbobbytables"

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Talks and Events"
  url = "#talks-and-events"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

[Languages.en]
  languageCode = "en-us"
